name: Build AppImage

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build AppImage for x86_64
    runs-on: ubuntu-latest
    container: opensuse/leap:15.2

    env:
      ARCH: x86_64
      APPIMAGE_EXTRACT_AND_RUN: 1

    steps:
      - name: Install dependencies
        run: |
          set -x
          . /etc/os-release
          zypper -n addrepo https://download.opensuse.org/repositories/home:kfreitag/openSUSE_Leap_"$VERSION_ID"/home:kfreitag.repo
          zypper --gpg-auto-import-keys refresh
          zypper -n install ImageMagick deskew wget libqt5-qtbase-devel Mesa-libGL-devel extra-cmake-modules git cmake gcc gcc-c++ ninja libqt5-linguist-devel

      - uses: actions/checkout@v2
        with:
          submodules: recursive

          # need to get the tags for git describe to work properly
          fetch-depth: 0

      - name: Build AppImage
        run: bash -ex ci/build.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage x86_64
          path: PDFQuirk*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/PDFQuirk*.AppImage*
